// api/checklist.js
// Generates a downloadable CSV checklist for a set
// GET /api/checklist?set=me05&type=master

const R2_BASE = process.env.CF_R2_PUBLIC_URL || 'https://pub-20ee170c554940ac8bfcce8af2da57a8.r2.dev';

const SET_NAMES = {
  'sv01':'Scarlet & Violet Base Set','sv02':'Paldea Evolved','sv03':'Obsidian Flames',
  'sv3pt5':'Pokemon 151','sv04':'Paradox Rift','sv4pt5':'Paldean Fates',
  'sv05':'Temporal Forces','sv06':'Twilight Masquerade','sv6pt5':'Shrouded Fable',
  'sv07':'Stellar Crown','sv08':'Surging Sparks','sv8pt5':'Prismatic Evolutions',
  'sv09':'Journey Together','sv10':'Destined Rivals',
  'zsv10pt5':'Black Bolt','rsv10pt5':'White Flare',
  'me01':'Mega Evolution','me02':'Phantasmal Flames','me02pt5':'Ascended Heroes',
  'me03':'Perfect Order','me04':'Chaos Rising','me05':'Pitch Black',
};

const RARITY_ORDER = [
  'Common','Uncommon','Rare','Double Rare',
  'Illustration Rare','Art Rare',
  'Ultra Rare',
  'Special Illustration Rare','Black White Rare',
  'Hyper Rare','Mega Hyper Rare','Mega Attack Rare','Treasure Rare',
];

const SECRET_RARITIES = new Set([
  'Illustration Rare','Art Rare','Special Illustration Rare','Ultra Rare',
  'Hyper Rare','Mega Hyper Rare','Mega Attack Rare','Black White Rare','Treasure Rare',
]);

const RARITY_EMOJI = {
  'Common':                  'C',
  'Uncommon':                'U',
  'Rare':                    'R',
  'Double Rare':             'DR',
  'Illustration Rare':       'IR',
  'Art Rare':                'AR',
  'Ultra Rare':              'UR',
  'Special Illustration Rare': 'SIR',
  'Black White Rare':        'BWR',
  'Hyper Rare':              'HR',
  'Mega Hyper Rare':         'MHR',
  'Mega Attack Rare':        'MAR',
  'Treasure Rare':           'TR',
};

export default async function handler(req, res) {
  const { set, type } = req.query;
  if (!set) return res.status(400).json({ error: 'set parameter required' });

  const setName = SET_NAMES[set] || set;
  const master  = type === 'master';

  try {
    const r2Res = await fetch(`${R2_BASE}/data/${set}.json`);
    if (!r2Res.ok) throw new Error(`R2 ${r2Res.status}`);
    const data  = await r2Res.json();
    const cards = data.cards || [];
    if (cards.length === 0) throw new Error('No cards found');

    // Normalize all rarities
    const normalized = cards.map(c => ({
      ...c,
      rarity: normalizeRarity(c.rarity || ''),
    }));

    // Sort by rarity tier then card number
    const sorted = [...normalized].sort((a, b) => {
      const ra = RARITY_ORDER.indexOf(a.rarity);
      const rb = RARITY_ORDER.indexOf(b.rarity);
      if (ra !== rb) return (ra === -1 ? 99 : ra) - (rb === -1 ? 99 : rb);
      return naturalSort(a.localId, b.localId);
    });

    // Group by rarity
    const groups = {};
    for (const card of sorted) {
      const r = card.rarity || 'Unknown';
      if (!groups[r]) groups[r] = [];
      groups[r].push(card);
    }

    const rows = [];

    // ── Title block ────────────────────────────────────────────────────────────
    rows.push([`${setName} ${master ? 'Master Set' : ''} Checklist`]);
    rows.push([`Generated by TCG Watchtower — tcgwatchtower.com`]);
    rows.push([`${cards.length} cards${master ? ` + reverse holos` : ''} • Set: ${set.toUpperCase()}`]);
    rows.push([]); // blank

    // ── Legend ─────────────────────────────────────────────────────────────────
    rows.push(['LEGEND']);
    rows.push(['Abbrev', 'Rarity', 'Pulls per box (approx)']);
    rows.push(['C',   'Common',                   'Circle symbol — ~6-7 per pack']);
    rows.push(['U',   'Uncommon',                 'Diamond symbol — ~2-3 per pack']);
    rows.push(['R',   'Rare',                     '1 black star — guaranteed 1 per pack']);
    rows.push(['DR',  'Double Rare',              '2 black stars — regular-art Pokemon ex']);
    rows.push(['IR',  'Illustration Rare',        '1 gold star — full-art non-Rule Box Pokemon']);
    rows.push(['AR',  'Art Rare',                 '1 gold star — used in Black Bolt/White Flare']);
    rows.push(['UR',  'Ultra Rare',               '2 foil stars — full-art textured Pokemon ex & Supporters']);
    rows.push(['SIR', 'Special Illustration Rare','2 gold stars — premium story-scene full art']);
    rows.push(['BWR', 'Black White Rare',         '2 gold stars — Black Bolt/White Flare exclusive']);
    rows.push(['HR',  'Hyper Rare',               '3 gold stars — gold-bordered cards']);
    rows.push(['MHR', 'Mega Hyper Rare',          'Gold star (black border) — gold-etched Mega ex, ~1 per 35 boxes']);
    rows.push(['MAR', 'Mega Attack Rare',         'Pink & green stars — pop-art attack illustrations, intro in Ascended Heroes']);
    rows.push(['TR',  'Treasure Rare',            'One Piece TCG exclusive rarity']);
    rows.push([]);

    // ── Summary ────────────────────────────────────────────────────────────────
    rows.push(['SET SUMMARY']);
    rows.push(['Rarity', 'Abbrev', 'Count', 'Collected', 'Remaining']);
    for (const rarity of RARITY_ORDER) {
      const group = groups[rarity];
      if (!group || group.length === 0) continue;
      rows.push([rarity, RARITY_EMOJI[rarity] || rarity, group.length, '', `=C-D`]);
    }
    const rhCount = master ? normalized.filter(c => !SECRET_RARITIES.has(c.rarity)).length : 0;
    if (master) rows.push(['Reverse Holos', 'RH', rhCount, '', '=C-D']);
    rows.push(['TOTAL', '', cards.length + (master ? rhCount : 0), `=SUM(D:D)`, `=SUM(E:E)`]);
    rows.push([]);

    // ── Card list grouped by rarity ────────────────────────────────────────────
    rows.push(['CARD LIST']);
    rows.push(['#', 'Card Name', 'Rarity', 'Abbrev', 'Have ✓', 'Grade', 'Notes']);

    for (const rarity of RARITY_ORDER) {
      const group = groups[rarity];
      if (!group || group.length === 0) continue;

      rows.push([]); // blank spacer
      rows.push([`── ${rarity.toUpperCase()} (${group.length} cards) ──`]);

      for (const card of group) {
        rows.push([
          padId(card.localId),
          card.name,
          card.rarity,
          RARITY_EMOJI[card.rarity] || '',
          '',   // Have ✓
          '',   // Grade (PSA/BGS)
          '',   // Notes
        ]);
      }
    }

    // ── Reverse holos ─────────────────────────────────────────────────────────
    if (master) {
      const rhCards = normalized.filter(c => !SECRET_RARITIES.has(c.rarity));
      rows.push([]);
      rows.push([`── REVERSE HOLOS (${rhCards.length} cards) ──`]);
      rows.push(['#', 'Card Name', 'Rarity', 'Abbrev', 'Have ✓', 'Grade', 'Notes']);
      for (const card of rhCards) {
        rows.push([
          `${padId(card.localId)} RH`,
          card.name,
          `${card.rarity} (Reverse Holo)`,
          'RH',
          '',
          '',
          '',
        ]);
      }
    }

    // ── Footer ────────────────────────────────────────────────────────────────
    rows.push([]);
    rows.push([`TCG Watchtower — tcgwatchtower.com — Free to use and share`]);

    // Encode
    const csv = rows.map(row =>
      row.map(cell => {
        const s = String(cell ?? '');
        return s.includes(',') || s.includes('"') || s.includes('\n')
          ? `"${s.replace(/"/g, '""')}"`
          : s;
      }).join(',')
    ).join('\r\n');

    const filename = `${setName.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${master ? 'master-set-' : ''}checklist.csv`;

    res.setHeader('Content-Type', 'text/csv; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.setHeader('Cache-Control', 'public, max-age=3600');
    res.status(200).send('\uFEFF' + csv);

  } catch (e) {
    res.status(500).json({ error: e.message });
  }
}

function normalizeRarity(r) {
  return r.split(' ').map(w => w ? w[0].toUpperCase() + w.slice(1).toLowerCase() : w).join(' ');
}

function padId(id) {
  const n = parseInt(id, 10);
  return isNaN(n) ? id : String(n).padStart(3, '0');
}

function naturalSort(a, b) {
  const na = parseInt(a, 10), nb = parseInt(b, 10);
  if (!isNaN(na) && !isNaN(nb)) return na - nb;
  return String(a).localeCompare(String(b));
}

